/**
 * types.ts
 *
 * Shared TypeScript interfaces for CivicLens.
 *
 * These types are the contract between the frontend and the backend API.
 * If the backend response shape changes, update here first and let the
 * TypeScript compiler surface every affected call site.
 */

// ---------------------------------------------------------------------------
// Core domain types
// ---------------------------------------------------------------------------

/**
 * Represents a single civic issue reported by a citizen.
 *
 * Lifecycle:
 *  1. Created client-side when a user submits a report.
 *  2. Enriched by the Gemini Vision + Pro pipeline on the backend
 *     (issueType, severity, department, reasoning, confidence).
 *  3. Stored and served back via GET /api/issues.
 *  4. Mutated via POST /api/issues/:id/upvote (reportCount increments).
 */
export interface CivicIssue {
  /** Unique issue identifier (UUID or numeric string from backend). */
  id: string;

  /** Short AI-generated title for the issue (e.g. "Dangerous Deep Crater Pothole"). */
  title: string;

  /** Full citizen-provided description of the issue. */
  description: string;

  /** Name of the municipal ward where the issue was reported. */
  ward: string;

  /** Latitude coordinate of the issue location. */
  lat: number;

  /** Longitude coordinate of the issue location. */
  lng: number;

  /** Public URL of the uploaded evidence image, or null if no image was provided. */
  imageUrl: string | null;

  /** AI-classified issue category (e.g. "Road Damage", "Waterlogging / Flooding"). */
  issueType: string;

  /** AI-assigned severity score from 1 (minor) to 10 (critical). */
  severity: number;

  /** Estimated radius of impact around the issue location (e.g. "200 meters"). */
  affectedRadius: string;

  /** Responsible municipal department recommended by the AI. */
  department: string;

  /** AI confidence in its classification, expressed as a percentage (0–100). */
  confidence: number;

  /** Step-by-step reasoning produced by the Gemini analysis pipeline. */
  reasoning: string;

  /** Number of citizens who have upvoted or corroborated this report. */
  reportCount: number;

  /** ISO 8601 timestamp of when the issue was first reported. */
  createdAt: string;

  /** True for the five pre-seeded demo issues served on first load. */
  isDemo?: boolean;

  /**
   * Set to false by the AI when the submitted description does not describe
   * a valid civic issue. Used to render the "Invalid Report" error state.
   */
  isValid?: boolean;

  /**
   * Follow-up questions generated by Gemini when it needs more information
   * before it can produce a confident analysis. Triggers the clarification panel.
   */
  clarificationQuestions?: string[];

  /**
   * Answers to the quick follow-up questions shown after the main form.
   * Sent to the backend alongside the description to enrich the AI context.
   */
  quickDetails?: {
    /** How long the issue has existed (e.g. "1-3 days", "More than a week"). */
    duration: string;
    /** How many people are affected (e.g. "My street", "Entire area"). */
    impact: string;
    /** Whether there is immediate danger (e.g. "Serious hazard", "Emergency"). */
    danger: string;
  };
}

/**
 * Computed health metrics for a single municipal ward.
 * Derived client-side from the active CivicIssue list.
 *
 * Health score formula: 100 − (issueCount × 6) − round(avgSeverity × 4),
 * clamped to [0, 100].
 */
export interface WardHealth {
  /** Display name of the ward. */
  name: string;

  /** Computed health score from 0 (critical) to 100 (excellent). */
  healthScore: number;

  /** Total number of active issues in this ward. */
  issueCount: number;

  /** Mean severity of all active issues, rounded to one decimal place. */
  averageSeverity: number;
}
